### ISSUE TITLE
Embedar o "Plantão Coronavírus" para fins de teste

### ISSUE THREAD

**Issue by ItaloRod** [EscolaDeSaudePublica/iSaude#12]
esse embed da susi será da mesma forma do "Plantão Coronavirus"

**Comment by uira** [comment]
E aí, isso aqui tá em que lugar da fila?

**Comment by ItaloRod** [comment]
> 
> 
> E aí, isso aqui tá em que lugar da fila?

vou iniciar agora, já que estou esperando a confecção das spashscreens

**Comment by ItaloRod** [comment]
Consegui integrar usando o React (O Plugin que tem no próprio repositório rasa webchat ). Porém ainda não consigo me conectar ao servidor. Acredito que há alguma configuração que não esteja correta.
