### ISSUE TITLE
Verificar a aplicabilidade do Bold no iSaude

### ISSUE THREAD

**Issue by ItaloRod** [EscolaDeSaudePublica/iSaude#15]
Como projeto do Bold é em React, verificar a viabilidade para o vueJS
https://bold.bridge.ufsc.br/pt/about

**Comment by ItaloRod** [comment]
O Bold não funciona em Vue pois ele necessita do React e React-dom para funcionar.

**Comment by rodrigoplimafreire** [comment]
Então, qual é a conclusão?

- É possível a gente utilizar o Bold como Design System, ou complica na execução do projeto? 

- Se fizermos esta migração a equipe de desenvolvimento terá algum prejuízo?

**Comment by ItaloRod** [comment]
Conclusão:
Da forma que o projeto está estruturado hoje, não há a compatibilidade de tecnologia. O que torna inviável.
É possível sim a utilização do Design System do Bold através da migração da tecnologia do sistema.(ReactJs + Capacitor somente). O impacto e prejuízo para o uso é baixo visto que o projeto ainda está no começo.
