### ISSUE TITLE
Solicitar Logo do aplicativo e ícones

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/iSaude#6]
iSaúde - O Super App da Saúde Pública

Briefing:  http://bit.ly/Apresenta-iSaude

**Comment by uira** [comment]
# Referências

![image](https://user-images.githubusercontent.com/89998/78855243-c52b7a80-79f9-11ea-807e-7d42fa3af0c5.png)

![image](https://user-images.githubusercontent.com/89998/78855262-d07ea600-79f9-11ea-980d-8f4e24958a4c.png)

![image](https://user-images.githubusercontent.com/89998/78855271-d5435a00-79f9-11ea-9a51-c08054c8efcf.png)

![image](https://user-images.githubusercontent.com/89998/78855278-db393b00-79f9-11ea-9f36-80e35015a9e6.png)

![image](https://user-images.githubusercontent.com/89998/78855287-deccc200-79f9-11ea-823c-c05ca999278c.png)

![image](https://user-images.githubusercontent.com/89998/78855302-e42a0c80-79f9-11ea-9f2d-e6f4b4655a5d.png)

![image](https://user-images.githubusercontent.com/89998/78855310-e8562a00-79f9-11ea-9fee-e66c258e129d.png)

https://fontawesome.com/icons/heartbeat?style=solid

https://blog.fontawesome.com/covid-19-awareness-icons/

**Comment by wforte88** [comment]
![Teste_iSaude](https://user-images.githubusercontent.com/21333612/78933594-ee8ee980-7a7f-11ea-8202-126c7631dbe0.png)
![Teste_iSUS](https://user-images.githubusercontent.com/21333612/78933389-9bb53200-7a7f-11ea-8479-a4d6cf4c54c6.png)
![Splash](https://user-images.githubusercontent.com/21333612/78933393-9ce65f00-7a7f-11ea-812d-7fd1d49f0d62.png)
![Icon](https://user-images.githubusercontent.com/21333612/78933394-9d7ef580-7a7f-11ea-863c-aa82554b5909.png)

**Comment by wforte88** [comment]
![Logo_iSUS](https://user-images.githubusercontent.com/21333612/78934265-031fb180-7a81-11ea-9a65-667ee03aeaf0.png)
![Logo_iSaude](https://user-images.githubusercontent.com/21333612/78934266-0450de80-7a81-11ea-898f-0d0eec0724ca.png)

**Comment by ItaloRod** [comment]
Logo em forma Transparente
![Icon_iSaude fw](https://user-images.githubusercontent.com/20058085/79255587-e3abce80-7e5c-11ea-869e-e70ec63d999e.png)

**Comment by ItaloRod** [comment]
Assets gerados e serão anexados ao projeto no próxima atualização

**Comment by wforte88** [comment]
SVG
[icon_iSaude.gz](https://github.com/EscolaDeSaudePublica/iSaude/files/4517136/icon_iSaude.gz)
