### ISSUE TITLE
Implementar pushNotification no PWA

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/iSaude#8]

**Comment by ItaloRod** [comment]
implementado através do firebase e testado com sucesso no chrome. Só falta:
- [ ] Devido a politicas do Firefox, o sistema de push notifications precisa ser chamado através da ação de um botão. Precisamos implementar uma solução que viabilize esse navegador ou descarta.
- [ ] Implementar serviço de armazenamento dos tokens dos usuários. Segmentar e notificar baseado em seus grupos (papéis)

**Comment by ItaloRod** [comment]
Por tanto o Método de Autenticação será via Firebase. Já testado no Android e funcionando.
iOS em pendência até o momento

**Comment by ItaloRod** [comment]
Todos os processos para rodar push notifications no iOS. Estamos com dificuldade de testar devido a falta de um iPhone / iPad compatível
