### ISSUE TITLE
Gerar APP pra android e IOS

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [EscolaDeSaudePublica/iSaude#9]
https://www.pwabuilder.com/

**Comment by ItaloRod** [comment]
App Android Gerado. Porém sem como Testar a parte do iOS. Enviando para o TestFlight para tentar rodar o projeto.

**Comment by ItaloRod** [comment]
Android já foi gerado APK porém ainda não se encontra na loja. Contudo, a versão do iOS está no TestFlight tem testes controlados. Para poder disponibiliza-los na loja, precisamos das artes sobre o aplicativo que farão parte do dispositivo. Apple obriga a utilização dessas imagens
